
main:
  - identifier: blog
    name: Blog
    pageRef: /blog
    weight: 1
  - identifier: about
    name: About
    pageRef: /about
    weight: 2
  - identifier: contact
    name: Contact ↗
    url: "https://keyoxide.org/36B0B7553AE5A95B"
    weight: 3
  - identifier: search
    name: Search
    weight: 4
    params:
      type: search
social:
  - name: GitHub
    weight: 1
    url: "https://github.com/Searge"
    params:
      icon: github
  - name: Mastoodon
    weight: 2
    url: "https://twiukraine.com/@Searge"
    params:
      icon: mastodon
  - name: LinkedIn
    weight: 3
    url: "https://www.linkedin.com/in/searge/"
    params:
      icon: linkedin