sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.8

outputs:
  home: ['html']
  page: ['html']
  rss: ['rss']
  section: ['html']
  taxonomy: ['html']
  term: ['html']

services:
  googleAnalytics:
    ID: G-0BLVNDH5W7